# syntax=docker/dockerfile:1

FROM gradle:7.1.1-jdk11 AS build

COPY --chown=gradle:gradle . /buildDir

WORKDIR /buildDir
RUN gradle :report-microservice:build --no-daemon

FROM openjdk:11-jre-slim

EXPOSE 8083

RUN mkdir /app

COPY --from=build /buildDir/application/report-microservice/build/libs/*.jar /app/report-microservice.jar

ENTRYPOINT ["java", "-jar", "/app/report-microservice.jar"]
