# syntax=docker/dockerfile:1

FROM gradle:7.1.1-jdk11 AS build

COPY --chown=gradle:gradle . /buildDir

WORKDIR /buildDir
RUN gradle :patient-microservice:build --no-daemon

FROM openjdk:11-jre-slim

EXPOSE 8081

RUN mkdir /app

COPY --from=build /buildDir/application/patient-microservice/build/libs/*.jar /app/patient-microservice.jar

ENTRYPOINT ["java", "-jar", "/app/patient-microservice.jar"]
